## Лабораторная работа №1

При помощи функции loadtxt из пакета NumPy загрузите массив, содержащий данные о фильмах. 

In [216]:
import numpy as np

data = np.loadtxt('data.txt')
dataT = data.T

Описание столбцов:
1. Комедия (0 - нет, 1 - да)
2. Драма (0 - нет, 1 - да)
3. Семейные (0 - нет, 1 - да)
4. Год
5. Бюджет
6. Сборы
7. Продолжительность
8. Рейтинг

__Задание 1 (0.5).__

Сколько фильмов описано в данных?

In [219]:
len(data)

2345

__Задание 2 (0.5).__

Сколько комедий содержится в данных?

In [221]:
comedians = data[:,0] == 1
len(data[comedians == 1])

1110

__Задание 3 (1).__

Есть ли в данных фильмы, являющиеся одновременно комедией и драмой? Сколько их?

In [46]:
dataT = data.T
mask = (dataT[0] == 1.) & (dataT[1] == 1.)
len(mask[mask])

320

__Задание 4 (1).__

Найдите средний рейтинг по всем фильмам.

In [136]:
data.mean(axis=0)[7]

6.3651599147121409

__Задание 5 (1).__

Найдите среднюю продолжительность семейных фильмов.

In [138]:
mask = dataT[2] == 1.
data[mask].mean(axis=0)[6]

98.550684931506851

__Задание 6 (1).__

Найдите стандартное отклонение прибыли (сборы - бюджет) для драм?

In [224]:
data[dataT[1] == 1]
# mask = dataT[1] == 1.
# (data[mask,5] - data[mask,4]).std()

array([[  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          1.08493910e+09,   1.65000000e+02,   7.60000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          5.50000000e+08,   1.87000000e+02,   6.60000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          1.84503419e+09,   1.94000000e+02,   7.50000000e+00],
       ..., 
       [  1.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          4.16498000e+05,   9.90000000e+01,   5.60000000e+00],
       [  1.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+04,   8.90000000e+01,   6.30000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          4.24760000e+05,   7.70000000e+01,   6.90000000e+00]])

__Задание 7 (1).__

Выведите данные о фильме с самым низким рейтингом. Является ли фильм с таким рейтингом единственным?

In [167]:
res = min(data, key=lambda x: x[7])
len(data[data[:,7]== res[7]])

2

__Задание 8 (1).__

Среди фильмов с рейтингом выше 7.0 найдите доли фильмов по годам. Выведите их в порядке убывания.

In [168]:
dataT[films_rat_more_7][0]

array([ 2012.,  2010.,  2009., ...,  1994.,  1972.,  2004.])

In [176]:
films_rat_more_7 = data[:,7] > 7.0
films_rat_more_7
unique, counts = np.unique(data[films_rat_more_7][:,3], return_counts=True,)
sum_counts = sum(counts)
counts = counts/sum_counts
sorted(dict(zip(unique, counts)).items(), key=lambda x: -x[1])

[(2013.0, 0.047808764940239043),
 (2014.0, 0.047808764940239043),
 (2004.0, 0.041832669322709161),
 (2006.0, 0.041832669322709161),
 (2015.0, 0.041832669322709161),
 (2007.0, 0.039840637450199202),
 (2002.0, 0.037848605577689244),
 (2009.0, 0.037848605577689244),
 (2008.0, 0.035856573705179286),
 (2010.0, 0.035856573705179286),
 (1998.0, 0.03386454183266932),
 (1999.0, 0.03386454183266932),
 (2001.0, 0.03386454183266932),
 (1997.0, 0.029880478087649404),
 (2003.0, 0.029880478087649404),
 (2000.0, 0.027888446215139442),
 (2005.0, 0.027888446215139442),
 (2012.0, 0.027888446215139442),
 (1995.0, 0.021912350597609563),
 (2011.0, 0.019920318725099601),
 (1993.0, 0.017928286852589643),
 (1994.0, 0.013944223107569721),
 (1990.0, 0.011952191235059761),
 (1992.0, 0.011952191235059761),
 (1964.0, 0.0099601593625498006),
 (1980.0, 0.0099601593625498006),
 (1987.0, 0.0099601593625498006),
 (2016.0, 0.0099601593625498006),
 (1962.0, 0.0079681274900398405),
 (1974.0, 0.0079681274900398405),
 (1981.

__Задание 9 (1).__

Замените рейтинги фильмов на классы по следующему принципу:
* если рейтинг был меньше 5, заменим его на 3
* если рейтинг был от 5 до 7, заменм его на 2
* если рейтинг был больше 7, заменим его на 1

In [214]:
data1 = data[:]
data1[data[:,7] < 5,7] = 3
data1[(5 <=data[:,7]) & (data[:,7]<=7),7] = 2
data1[data[:,7]>7,7] = 1
data1

array([[  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          1.08493910e+09,   1.65000000e+02,   1.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00, ...,
          5.91794936e+08,   1.00000000e+02,   1.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00, ...,
          9.33959197e+08,   1.53000000e+02,   1.00000000e+00],
       ..., 
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          3.15113000e+06,   9.20000000e+01,   1.00000000e+00],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          6.00000000e+06,   9.30000000e+01,   2.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          4.24760000e+05,   7.70000000e+01,   2.00000000e+00]])

__Задание 10* (2).__

Проверьте, зависит ли класс фильма от бюджета.

In [215]:
np.corrcoef(data1[:,7], y=data1[:,4])

array([[ 1.        ,  0.02717585],
       [ 0.02717585,  1.        ]])

In [228]:
np.corrcoef(data1[:, 0:3], y=data1[:,4])

ValueError: all the input array dimensions except for the concatenation axis must match exactly